### ISSUE TITLE
Filtering column with Arabic alphabet error  

### ISSUE THREAD

**Issue by ahmednet0001** [MedicOneSystems/livewire-datatables#141]
I am trying to filter column with Arabic characters but I have this error 
LoadingStates.js:259 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range. at generateSignatureFromMethodAndParams (http://127.0)
![livewire datatable](https://user-images.githubusercontent.com/11617821/106963203-ec9dc180-6748-11eb-9ea9-033a07b31802.jpg)

**Comment by mahmod2000** [comment]
Hi @ahmednet0001 
You need to update the livewire version in your project
the issue is here: vendor/livewire/livewire/js/component/LoadingStates.js:259 and you need to change to this :
`function generateSignatureFromMethodAndParams(method, params) {
    return method + btoa(encodeURIComponent(params.toString()))
}`

after fixing, you need to npm run build or dev to render livewire js file and implement new changes in your project.

**Comment by ahmednet0001** [comment]
Hi @mahmod2000 
Thankyou for help .I try as you explained but the error is still there . When I look at inspect code in browser in network tab and js file ivewire/livewire.js?id=936e5d0fb0b76b631ba7  ,the function function generateSignatureFromMethodAndParams has old code although I have run 'npm run dev' 
Dose this command rebuild livewire js?

**Comment by mahmod2000** [comment]
Actually I don’t know how to rebuild  livewire js filea, I changed 2 files manually for now
You can search in livewire communities for that

**Comment by ahmednet0001** [comment]
@mahmod2000 Thanks . I published livewire J's to buplic folder and changed the code . It now working well 💯💯
