### ISSUE TITLE
COMPOSER UPDATE issues with PHP 8 installed. original version was installed on PHP 7.4

### ISSUE THREAD

**Issue by Triumfator-M** [MedicOneSystems/livewire-datatables#162]
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mediconesystems/livewire-datatables ^0.4.3 -> satisfiable by mediconesystems/livewire-datatables[v0.4.3].
    - mediconesystems/livewire-datatables v0.4.3 requires php ^7.2.5 -> your php version (8.0.2) does not satisfy that requirement.

**Comment by Triumfator-M** [comment]
This doesn't work if i change php requirements to^7.2.5|^8.0

**Comment by nathanaelytj** [comment]
Based on the #97 issue, there's already PR and it's merged to master. The bad news is that it's untagged release so to bypass the problem use `--ignore-platform-reqs`. The install command become `composer require mediconesystems/livewire-datatables --ignore-platform-reqs`.

Though this is a bad idea for long term solution since any packages that need specific PHP version and/or PHP extension but not activated/installed yet also got bypassed.
