### ISSUE TITLE
Actions column

### ISSUE THREAD

**Issue by tiagosimoesdev** [MedicOneSystems/livewire-datatables#21]
Would you accept a pull request that instead of a delete column , it has a actions column ? 

We can call like :

`` Column::actions('view','edit','delete')->label('actions')->alignRight() ``

View will go to clients/1
Edit will go to clients/1/edit
and delete remains the same

Maybe we can configure a variable for view_url , edit_url . What do you think ?

**Comment by marksalmon** [comment]
Yes, definitely, that's a great idea.

Could it work so that the arguments to the ```actions``` method would specify which actions were displayed, so that users could choose any combination of view/edit/delete?

Happy to have config variable for urls (and route names would be nice) but we should provide sensible defaults like you have suggested above. 

Also probably worth making separate blade partials for each button, so that users can publish and swap in their own icons as required - this is something I need to do more of throughout the package.

**Comment by tiagosimoesdev** [comment]
Yeah ,I'm working on it

**Comment by tiagosimoesdev** [comment]
Hi , 

Made it working like this:

``//config.livewire-datatables.php``
added
`` 'default_buttons'   =>  ['view', 'edit', 'delete']``

then in `users.table.php`

You can call like this 
`ActionsColumn::all()->label('ActionsTitle')`

in resources/views/livewire/datatables there's 4 new files

`//actions.blade.php`
```
<div class="mt-8 flex lg:flex-shrink-0 lg:mt-0">
    @foreach (config('livewire-datatables')['default_buttons'] as $button)
    @include('datatables::buttons.'.$button)
    @endforeach
</div>
```


`// /buttons/edit.blade.php`
```
<span>
    <button class="p-1 text-orange-600 rounded hover:bg-orange-600 hover:text-white">
        <x-icons.edit /></button>
</span>
```

**Comment by danielbehrendt** [comment]
@tiagosimoesdev Awesome! Any ETA for a release?

**Comment by tiagosimoesdev** [comment]
Hoping to hear from the package author , if he thinks it's a good approach so I can tidy up thinks and make a PR

**Comment by marksalmon** [comment]
That all looks good to me. Go ahead and make the PR 😀

**Comment by danielbehrendt** [comment]
@tiagosimoesdev Any updates on this? 😀

**Comment by tiagosimoesdev** [comment]
@danielbehrendt  made a PR last wekk , waiting for @marksalmon  response. Not sure if it's the best approach , hope we can discuss what's the best way to implement it :)

**Comment by danielbehrendt** [comment]
@marksalmon Any update on this? Do you seen any problem with the PR?

**Comment by marksalmon** [comment]
please see comment in #25
