### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by LewisLarsen** [MedicOneSystems/livewire-datatables#26]
Hey there,

Could the package potentially be bumped up to support Laravel 8? With Laravel 8 coming in a few days, I imagine there will be a bunch of people that would be interested in using this with new projects. (Me! I'm one of these people! 😄) 

The package currently has ` illuminate/support ^7.0 ` support which Laravel 8 doesn't like. 

```
 Problem 1
    - Installation request for mediconesystems/livewire-datatables ^0.3.1 -> satisfiable by mediconesystems/livewire-datatables[v0.3.1].
    - Conclusion: remove laravel/framework 8.x-dev
    - Conclusion: don't install laravel/framework 8.x-dev
    - mediconesystems/livewire-datatables v0.3.1 requires illuminate/support ^7.0 -> satisfiable by illuminate/support[7.x-dev, v7.0.0,
```

Amazing package by the way!

Lewis

**Comment by marksalmon** [comment]
Hi Lewis,

Thanks, I’m pleased you like it. Yes, don’t worry, I too am eagerly
awaiting the release of Laravel 8 and will be upgrading as soon as I can
this week. Also Livewire 2 should be coming soon so that will be supported
too. If you want to speed things up please feel free to make a PR 😉

BW

Mark

**Comment by jongravois** [comment]
This is Livewire Datatables done RIGHT and I am looking forward to the Laravel 8 bump as well as the Livewire 2 bump!!!
