### ISSUE TITLE
Datatable displayed vertically

### ISSUE THREAD

**Issue by marcoroma** [MedicOneSystems/livewire-datatables#521]
Hi! I've a strange issue, I've created a simple datatable, but both the header and the data are showed vertically (like 1 column and all rows). 
Where I do Wrong?

    public function columns()
    {
        return [

            Column::name('id')
                ->label('ID')->sortBy('id'),

            Column::name('name')
                ->editable(),

            Column::name('description')
                ->editable(),

            DateColumn::name('activation_date')
                ->editable(),

        ];
    }
`

Thank you very much!

**Comment by renardudezert** [comment]
Hi !
I encountered exactly the same issue with a fresh installation of Laravel (9). The solution for me was to [publish config and assets ](https://github.com/MedicOneSystems/livewire-datatables#optional)

I hope this will help you !

**Comment by marcoroma** [comment]
Hi, thank you very much for your reply! 
I've made a fresh installation of Laravel 9 and now I published config and asset with the command indicated, but I've the same problem.. Have you configured something in those files?

**Comment by renardudezert** [comment]
Hi, you're welcome ;)
Laravel does not include tailwind by default since version 9. Instead, Mix has been replaced by Vite.

So you have to install tailwind and configure vite to use it. I advise you to follow [this blog post](https://dev.to/sureshramani/how-to-install-tailwind-css-3-in-laravel-9-with-vite-3-4hl1) which explains how to do it.

Regards

**Comment by marcoroma** [comment]
Thank you very much, I run npm run build and that's work!
