### ISSUE TITLE
Searchable not working when added to a column from a relationship

### ISSUE THREAD

**Issue by dotmarn** [MedicOneSystems/livewire-datatables#573]
`    public function builder()
    {
        return EmployeeDetail::query()->with('user')->where('company_id', 1);
    }`

`  public function columns()
    {
        return [
            Column::name('user.username')
                ->defaultSort('asc')
                ->searchable()
                ->label('Staff ID')->unwrap(),

            Column::raw("CONCAT(firstname, ' ', lastname) AS name")
                ->searchable()
                ->label('Name')->unwrap(),
        ];
    }`

It gives the error below

<img width="1440" alt="image" src="https://github.com/MedicOneSystems/livewire-datatables/assets/18660010/594ef1f4-e330-4991-bd46-bc381c965901">

**Comment by dotmarn** [comment]
I solved this by using using the joins instead of relationship.

**Comment by dotmarn** [comment]
@emresasi  I used leftJoin for the tables involved instead of using relationship and the search didn't break.

**Comment by emresasi** [comment]
@dotmarn I understand that that process will not work for me because a deal has more than one contact, so I want to show your transaction collectively in that column without using lefjoin 
```
Column::callback(['users.name', 'user.surname'], function ($name) , $surname) {
                 return $name." ".$surname;
             })
``` 
You should be able to solve it like this :) 
My process only gives count in this way, so I can't solve it anyway. I haven't found a solution for days.
