### ISSUE TITLE
Page Not Formatted 

### ISSUE THREAD

**Issue by desyashasyi** [MedicOneSystems/livewire-datatables#77]
I have installed Livewire-datatable and tried intermediate table. However, I have difficulties, the table page showed as the image. What is the problem
![Screen Shot 2020-11-09 at 12 58 26](https://user-images.githubusercontent.com/48233515/98505370-975a2d00-228b-11eb-8ef6-5638df693f26.png)

**Comment by Corrado2601** [comment]
Try npm install

**Comment by GustavoFenilli** [comment]
Did you find a solution? having the same problem right now

Did run npm install and npm run dev to run laravel mix, yet having the exact same result.

**Comment by xrezut** [comment]
This happens because the package uses Tailwind CSS, and requires this to be present. You can either load the styles through tailwind cdn by putting this in your head tag. `<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">` which should fix it, or alternatively follow the tailwind installation process at: https://tailwindcss.com/docs/guides/laravel#setting-up-tailwind-css
